# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ping Pong en la oficina
email: hola@rodrigo-ibarra.com
description: > # this means to ignore newlines until "baseurl:"
  Jugando Ping Pong en la oficina para distraernos durante la comida...
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  rodrigoibarra

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids:       true
  entity_output:  as_char
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
